plugins:
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-yard

AllCops:
  NewCops: enable
  SuggestExtensions: true
  Exclude:
    - 'bin/**/*'
    - 'out/**/*'
    - 'vendor/**/*'
    - 'doc/**/*'

# Don't let long declarations and invocations to contribute to method length.
# This is preferable over squeezing them onto a single line.
Metrics/MethodLength:
  CountAsOne:
    - array
    - method_call
    - hash

# Exclude our main gem include from the file naming convention, to keep it
# consistent with the gem name.
Naming/FileName:
  Exclude:
    - 'lib/cfa-eng-cli.rb'
    - 'README.md'
    - 'CLAUDE.md'

# Count multi-line hashes and arrays in examples as one line.
RSpec/ExampleLength:
  CountAsOne:
    - array
    - method_call
    - hash

# Favor more reusable helpers.
RSpec/MultipleMemoizedHelpers:
  Max: 10
